# -*- coding: utf-8 -*-
"""churn_api_flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhm0NORH68PrLUeLx-cXQ6TDa72rlbji
"""

from flask import Flask, request, jsonify
import joblib
import numpy as np

app = Flask(__name__)

# Load the model and preprocessing tools
model = joblib.load("best_rf_model.joblib")
scaler = joblib.load("scaler.joblib")
lda = joblib.load("lda.joblib")

@app.route('/')
def home():
    return "Customer Churn Prediction API is up!"

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.json['features']  # Expecting a list of numerical features
        data = np.array(data).reshape(1, -1)
        data_scaled = scaler.transform(data)
        data_lda = lda.transform(data_scaled)
        prediction = model.predict(data_lda)
        return jsonify({'prediction': int(prediction[0])})
    except Exception as e:
        return jsonify({'error': str(e)})

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
    app.run(debug=True)
